[MatchFixer]

; StarCraft Match Fixer Mod!
; Homepage: https://github.com/helloimhana123/starcraft-match-fixer

; Game speed from 0 ("Slowest"), to 6 ("Fastest")
; -1 to leave value unchanged.
GameSpeed = 6

; Latency frames from 1 to 20.
; -1 to leave value unchanged.
LatencyFrames = -1
